### ISSUE TITLE
Modifica struttura tabella

### ISSUE THREAD

**Issue by Doc73** [imcatta/restrizioni_regionali_covid#1]
Mi permetterei di suggerire una diversa struttura per la tabella, tale che abbia la data sulle ordinate e le regioni sulle ascisse, in questo modo:

```
data,regione1,regione2, ... regione20
giorno1,giallo,rosso, ... bianco
giorno2,bianco,rosso, ... verdone
...
```
Credo che in questo modo sarebbe più leggibile.

Cordiali saluti e grazie mille,
Domenico

**Comment by imcatta** [comment]
Grazie mille per il suggerimento. Senza dubbio la struttura proposta può risultare più comoda in diversi contesti, ma ho deciso di mantenere il formato attuale per due ragioni:

1. Per essere coerente con la [struttura utilizzata nel repository della protezione civile](https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-covid19-italia.md#formato-dei-dati)
2. Per retrocompatibilità, ossia per non "rompere" gli script che stanno utilizzando questo dataset


PS: 🚀 per bianco rosso verdone
