### ISSUE TITLE
imprecisione dati Lombardia-Inizio novembre

### ISSUE THREAD

**Issue by danielezerbini** [imcatta/restrizioni_regionali_covid#2]
Buonasera, 
ho notato che la lombardia è segnata in zona gialla dal 6 al 19 novembre, mentre in realtà dovrebbe essere segnata come rossa [link](https://www.ilsussidiario.net/news/lombardia-zona-rossa-cosa-cambia-dal-6-novembre-misure-scuole-spostamenti-e/2089900/).
@imcatta

**Comment by imcatta** [comment]
Grazie mille per la segnalazione. Il problema (che affliggeva tutte le regioni non "gialle" al 6 novembre 2020) ora è stato risolto.
