### ISSUE TITLE
Script impazzito....

### ISSUE THREAD

**Issue by jumpjack** [imcatta/restrizioni_regionali_covid#4]
Lo script per la generazione del file delle zone è impazzito, adesso crea un file che arriva fino al 2100, con centinaia di migliaia di elementi!

**Comment by Doc73** [comment]
Sì, probabilmente dipende da questo bug: [https://github.com/pcm-dpc/COVID-19/issues/1160](https://github.com/pcm-dpc/COVID-19/issues/1160)
Speriamo risolvano presto a monte

**Comment by imcatta** [comment]
Grazie per la segnalazione. Come indicato da @Doc73 il problema era legato ad un bug nel repository della protezione civile. Ora dovrebbe essere tutto risolto.

**Comment by jumpjack** [comment]
Confermo:
https://win98.altervista.org/coronavirus/grafico-colori-regioni-covid-zone-v4.html

Comunque basta correggere gli script che leggono i dati originali in modo da ignorare le date oltre una certa data.
